language: java

before-install:
  - mvn install:install-file -Dfile=AbsoluteLayout.jar -DgroupId=unknown.binary -DartifactId=AbsoluteLayout -Dversion=SNAPSHOT -Dpackaging=jar

jdk:
  - oraclejdk8

addons:
  srcclr: true
  sonarqube: true
